module.exports={
    HOST:'mysql-129601-0.cloudclusters.net',
    USER:'admin',
    PASSWORD:'gdz9feFu',
    DB:'sen',
    dialect:'mysql',
    pool:{
        max:5,
        min:0,
        acquire:30000,
        idle:10000
    }
}